### ISSUE TITLE
Select not rendering if containing an option with a disabled attribute

### ISSUE THREAD

**Issue by ghost** [krescruz/angular-materialize#174]
## Issue

The select is not rendering when one of the `<option>` has a `disabled` attribute
However when entering this into the console: `$('select').material_select();` the select is rendered
## Link replicating the bug

[http://jsfiddle.net/nsap8ow1/3/](http://jsfiddle.net/nsap8ow1/3/)

**Comment by webbiesdk** [comment]
I can only replicate it when it is the first select that has the `disabled` attribute, if i put the attribute on all but the first one, it renders just fine. 

But it is a bug, and i can replicate it, and if it works when you run `$('select').material_select();` then it sounds like a bug with our code. 

I'll look at it later.

**Comment by dremy** [comment]
I have noticed am I am having this same issue. I have commented out the first disabled option in the mean while, but it would be nice to figure out whats happening.

**Comment by ivanhuay** [comment]
i have the same issue :sob:

**Comment by webbiesdk** [comment]
I pushed some code that fixed the issue when i tested it, please confirm if it fixed it for you guys.

**Comment by ghost** [comment]
This is still not working for me... still need to manually execute `$('select').material_select();` to render it

**Comment by webbiesdk** [comment]
Ok same deal, please test if it works for you. 

This is an updated JSFiddle, where i copy-pasted the new angular-materialize.js: http://jsfiddle.net/ggzs2jt4/1/

**Comment by ghost** [comment]
Almost... it's only rendering if the values are static, as in the JSFiddle. If the data come from a promise, the select is not updated (whereas it is without the `disabled` attribute)

**Comment by webbiesdk** [comment]
Ok, i just removed that part. 

The part was there to try to minimize the amount of re-initializations that were performed, and I couldn't get it to do any optimization, and still work in your case, so now its gone. 

I tested with an application that changed the value back and forth, and it worked for me, so please test.
